version: '3'

services:

  php-fpm:
    container_name: small-shop_php-fpm
    image: small-shop/php-fpm
    build:
      context: .
    entrypoint:
      - php
      - -v

  php-fpm-local:
    container_name: small-shop_php-fpm-local
    image: small-shop/php-fpm-local
    build:
      dockerfile: local.Dockerfile
      context: .
    volumes:
      - ./:/var/www:cached
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
    network_mode: bridge
    depends_on:
      - php-fpm
    links:
      - mysql

  nginx:
    container_name: small-shop_nginx
    image: nginx:1.15
    volumes:
      - ./:/var/www:cached
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./storage/logs/nginx/:/var/log/nginx:cached
    network_mode: bridge
    ports:
      - 80:80
    links:
      - php-fpm-local

  mysql:
    container_name: small-shop_mysql
    image: mysql:5.6
    volumes:
      - ./storage/database/:/var/lib/mysql:cached
    environment:
      - "MYSQL_DATABASE=laravel"
      - "MYSQL_USER=laravel"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
      - "TZ=UTC"
    network_mode: bridge
    ports:
      - 33060:3306
